### PR TITLE
ui: Mark 3 strings translatable

### PR DESCRIPTION
**Pull request by sabriunal**
- Enter a tag name
- PDF
- CVS

### CODE REVIEW

**Comment by nlogozzo** [comment]
@fsobolev Could you run GeneratePot and UpdatePo?

**Comment by sabriunal** [comment]
I'm using the flatpak-builder. Which commands do I need to run?

Could you please provide updated instructions for it?

**Comment by nlogozzo** [comment]
You need to have `dotnet` 7 installed...then from the root of the repo run:
- `dotnet tool restore`
- `dotnet tool install --global GetText.NET.Extractor` (which you might need .NET 6 for this to install...which is fine you can install 6 and 7 side by side)
- `dotnet cake --target=GeneratePot && dotnet cake --target=UpdatePo` (this will make the new .pot file and apply it to existing .po files)

**Review by nlogozzo — APPROVED** [review]

**Comment by sabriunal** [comment]
It seems a lot of work. Thanks for updating them.

**Comment by nlogozzo** [comment]
> It seems a lot of work. Thanks for updating them.

😅 that's why we just take care of it haha

**Pull request merged**
