### PR TITLE
Fixes

### LINKED ISSUE #649: Adding receipts causes Denaro to crash
This is a bug I got first a while ago when I first tried out Denaro. I couldn't file a bug report at that time. Today I opened Denaro in a long time and was surprised to find out that the same bug was still there and I couldn't find any reports of this issue here. This makes me believe that this is something that has to do with my particular setup.  Writing this here just incase it isn't.

### Steps to reproduce
1. Create a new checking account
2. Add an expense
3. Write a name & amount and upload a jpg image as the receipt.
4. Click the view button. *(This didn't work for me the first time, but that was because I had restricted Denaro's permission to Documents directory only. Resetting all permissions to default made this work.)*
5. Click Add
6. Open the transaction again.
7. Now sometimes it opens but you sometimes it crashes.
8. If it opens try viewing the reciept and either it crashes or does nothing when clicking the view button.
9. Sometimes when it crashes, there is no logs output in the terminal but most times there is.

Here is the output printed when it crashes:
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Image`1'.
   at SixLabors.ImageSharp.Image.ThrowObjectDisposedException(Type type)
   at SixLabors.ImageSharp.Image.EnsureNotDisposed()
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Clone(Image source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Clone(Image source, Action`1 operation)
   at NickvisionMoney.Shared.Models.Transaction.Clone() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Transaction.cs:line 163
   at NickvisionMoney.Shared.Controllers.TransactionDialogController..ctor(Transaction transaction, Dictionary`2 transactions, Dictionary`2 groups, Boolean canCopy, String transactionDefaultColor, CultureInfo cultureNumber, CultureInfo cultureDate) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/TransactionDialogController.cs:line 105
   at NickvisionMoney.Shared.Controllers.AccountViewController.CreateTransactionDialogController(UInt32 id) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 522
   at NickvisionMoney.GNOME.Views.AccountView.EditTransaction(Object sender, UInt32 id) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 884
   at NickvisionMoney.GNOME.Controls.TransactionRow.Edit(Button sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Controls/TransactionRow.cs:line 171
   at GObject.Signal`1.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
```

This warning is also printed every time Denaro starts up, so I don't think its related but here it is anyway:
```

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 16:29:49.551: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 16:29:49.551: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
```
 
App version: 2023.6.2 (flatpak)
 OS: EndeavourOS
 DE: Gnome 44.3

*PS: I saw that there was a new stable release 8 hours ago but flathub hasn't picked up on it yet (atleast for me). I tried using the one from flathub-beta (2023.8.0) and it doesn't crash or produce any logs when trying to view the receipt, but still won't show it.*

Edit:
Adding the troubleshotting info from the app here:
```
org.nickvision.money
2023.6.2
GTK 4.10.4
libadwaita 1.3.3
Flatpak
en-CA
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC=en_CA.UTF-8
LC_TIME=en_CA.UTF-8
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY=en_CA.UTF-8
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER=en_CA.UTF-8
LC_NAME=en_CA.UTF-8
LC_ADDRESS=en_CA.UTF-8
LC_TELEPHONE=en_CA.UTF-8
LC_MEASUREMENT=en_CA.UTF-8
LC_IDENTIFICATION=en_CA.UTF-8
LC_ALL=
```

### LINKED ISSUE #650: Transactions default color
In transaction window, Group color defaults to **Use unique color**. 

Is it possible to have an option to use **Use group color** by default.

Screenshot_20230819_073319

### LINKED ISSUE #655: Index was out of range error crashes Denaro
Hi, I got this error while I was checking my translation.

It occured when I click a button.

- Version: 9157f69f2cb2c2c9193dfdc1e9f36ebf7690c690 build using flatpak-builder as Flatpak.
- OS: Ubuntu 23.04

[money.webm](https://github.com/NickvisionApps/Denaro/assets/6218679/987f5b37-d426-41d7-9754-67bbb8ef0e7f)

```
flatpak run --verbose org.nickvision.money

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 17:42:52.949: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 17:42:52.949: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
UnhandledException - unhandled exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NickvisionMoney.GNOME.Views.AccountView.OnDateRangeStartYearChanged() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 1252
   at NickvisionMoney.GNOME.Views.AccountView.<.ctor>b__69_21(Object sender, NotifySignalArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 207
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)

```

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #649 
Closes #650
Closes #655

### CODE REVIEW

**Comment by JoseBritto** [comment]
Hi, it seems like  this doesn't fix #649 
In the current version the crash no longer happens but the view receipt button still doesn't work. 

It seems to be caused by this overwriting the current value of Transaction.Receipt loaded from the database
https://github.com/NickvisionApps/Denaro/blob/3965087a0e4257797e6ebd1a1bc1e7563d66059d/NickvisionMoney.Shared/Controllers/TransactionDialogController.cs#L344-L360

when called from here:
https://github.com/NickvisionApps/Denaro/blob/3965087a0e4257797e6ebd1a1bc1e7563d66059d/NickvisionMoney.GNOME/Views/TransactionDialog.cs#L434

**Comment by nlogozzo** [comment]
> Hi, it seems like this doesn't fix #649 In the current version the crash no longer happens but the view receipt button still doesn't work.
> 
> It seems to be caused by this overwriting the current value of Transaction.Receipt loaded from the database
> 
> https://github.com/NickvisionApps/Denaro/blob/3965087a0e4257797e6ebd1a1bc1e7563d66059d/NickvisionMoney.Shared/Controllers/TransactionDialogController.cs#L344-L360
> 
> when called from here:
> 
> https://github.com/NickvisionApps/Denaro/blob/3965087a0e4257797e6ebd1a1bc1e7563d66059d/NickvisionMoney.GNOME/Views/TransactionDialog.cs#L434

Ah yes, that seemed to be it...try running from the latest commit and let me know if it's fixed.

**Comment by JoseBritto** [comment]
> @JoseBritto Can you confirm the fix with the latest commit?

Yep. That fixed it. 
Although now I can't seem to delete an attachment

**Comment by nlogozzo** [comment]
> Although now I can't seem to delete an attached receipt

Ah ok, I'm going to rework the receipt code haha...give me a few

**Comment by JoseBritto** [comment]
What do you think about saving the receipt (if it exists) to a file from the constructor? 
That way the receipt path will be populated always and https://github.com/NickvisionApps/Denaro/pull/659/commits/2c8f454a704c0076e8b6201787ae5326df62e0f5 won't be needed anymore. I didn't think of this earlier otherwise I would have opened a pr with the issue. I'm not sure if there is any drawbacks to that.

Also, probably unrelated to this, denaro currently writes the image to the home directory. Can we not do that? Now that windows is no longer supported as a platform, hardcoding the /tmp directory wouldn't be an issue. Maybe also set the permission on the file to 600 to remove any privacy concerns if its a shared system. Should I open another issue for this? or a pr?

**Comment by nlogozzo** [comment]
> What do you think about saving the receipt (if it exists) to a file from the constructor?
That way the receipt path will be populated always and https://github.com/NickvisionApps/Denaro/commit/2c8f454a704c0076e8b6201787ae5326df62e0f5 won't be needed anymore. I didn't think of this earlier otherwise I would have opened a pr with the issue. I'm not sure if there is any drawbacks to that.

> Also, probably unrelated to this, denaro currently writes the image to the home directory. Can we not do that? Now that windows is no longer supported as a platform, hardcoding the /tmp directory wouldn't be an issue. Maybe also set the permission on the file to 600 to remove any privacy concerns if its a shared system. Should I open another issue for this? or a pr?

No it's ok I'll take care of it all in the rewrite now

**Comment by JoseBritto** [comment]
Great. Thanks!

**Comment by nlogozzo** [comment]
@JoseBritto Ok try the latest commit...I also moved storing the temp picture for opening to Denaro's config folder and the file will get cleaned up as you use the application

**Comment by JoseBritto** [comment]
Yes it works now. Thanks!

**Comment by JoseBritto** [comment]
Hey, sorry to bring this up now but #655 seems to be not fixed too. (int)_startYearDropDown.GetSelected() seems to retrun -1 sometimes. More accurately _startYearDropDown.GetSelected() returns uint.max_value which seems to get converted to -1 somehow. The same happens for _endYearDropDown.

Here's how to reproduce:

1. In the calendar view change from 2023 to another year that has no transactions, say 2022.
2. Click the view current month button.
3. Denaro will crash

I think I found the problematic line. Its 1206 in AccountView.cs
```
        var selectedYearIndex = (uint)_controller.YearsForRangeFilter.IndexOf(selectedYear.ToString());
```
Here the indexOf will return -1 for 2022 which will get converted to uint.MAX_VALUE

**Comment by nlogozzo** [comment]
> Hey, sorry to bring this up now but #655 seems to be not fixed too. (int)_startYearDropDown.GetSelected() seems to retrun -1 sometimes. More accurately _startYearDropDown.GetSelected() returns uint.max_value which seems to get converted to -1 somehow. The same happens for _endYearDropDown.
> 
> Here's how to reproduce:
> 
>     1. In the calendar view change from 2023 to another year that has no transactions, say 2022.
> 
>     2. Click the view current month button.
> 
>     3. Denaro will crash
> 
> 
> I think I found the problematic line. Its 1206 in AccountView.cs
> 
> ```
>         var selectedYearIndex = (uint)_controller.YearsForRangeFilter.IndexOf(selectedYear.ToString());
> ```
> 
> Here the indexOf will return -1 for 2022 which will get converted to uint.MAX_VALUE

@JoseBritto Ah found it...made it so it won't try to select if the year doesn't have transactions...try now

**Comment by JoseBritto** [comment]
Yes. That worked. Shouldn't it show the no transactions found screen on pressing that button? Currently it just returns if the year is not found

**Comment by nlogozzo** [comment]
> Shouldn't it show the no transactions found screen on pressing that button? Currently it just returns if the year is not found

It could but since the button doesn't do anything as the year doesn't exist, the `Select Range` expander isn't turned on (which controls the filtering) so I don't see a need to do anything else.

**Comment by JoseBritto** [comment]
Oh okay. So it should all be good then. Thanks a lot!

**Comment by nlogozzo** [comment]
No thank you for finding these issues and working with me for fixes 😊

**Comment by nlogozzo** [comment]
Going to implement #656 then probably release a beta :)

**Comment by JoseBritto** [comment]
Nice. I'm looking forward to it. Let me know if there is something else I can help with. I would love to contribute to this project but not sure where to start.

**Comment by nlogozzo** [comment]
I mean feel free to look at an of the unassigned issues you may think you can accomplish and i'll assign it to you to work on...if you have any questions about the codebase and it's structure feel free to ask anytime! Join our matrix room too it will probably be easier to communicate than through GitHub

**Comment by JoseBritto** [comment]
Okay thanks. I will take a look. I joined matrix yesterday :)

**Pull request merged**
