### PR TITLE
Show amounts based on transactions shown + Sidebar Changes

### LINKED ISSUE #366: Show Amounts Based On Transactions Shown
From @fsobolev :
> What would be nice is if overview (and maybe groups too) would show numbers for filtered transactions. I think this can be considered, it doesn't add any complexity for users to work with, but we need to decide how the app should treat future transactions in this case. @nlogozzo

So basically I think it will show the number of transactions shown in the transactions list (including future transactions if they are shown in the list)

We can add a row underneath the `Expense` row in the overview section to show the `# of Transactions Shown: _` and then we can find a place for each group row to show the number of transactions shown in the list that belong to that group.

### LINKED ISSUE #503: Toggle selection of all groups
From #348:

> Turn the "Reset Groups Filter" into a toggle button that enables/disables all groups. This way I need at most 3 clicks, if I want to see the transactions of one specific group. Right now, I have to disable all other groups one by one.

I don't think the clear groups button should become a toggle, but a new button should be added. Not sure where to place it, but I will think about this.

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #366 
Closes #503

### CODE REVIEW

**Comment by nlogozzo** [comment]
Ok, PR ready!
Code is a little messy, but it will get cleanup up in the rewrite to fix #546 ... either way the feature is there

**Comment by nlogozzo** [comment]
I think maybe, when a group is unchecked, and when income/expense is unchecked, the amount label should be hidden, that way the user doesn't think that the group's transactions were deleted or that the balance is actually `0`, just the transactions are not filtered so there is no amount for it, thus it should be hidden

**Comment by nlogozzo** [comment]
> I think maybe, when a group is unchecked, and when income/expense is unchecked, the amount label should be hidden

Implemented with https://github.com/NickvisionApps/Denaro/pull/557/commits/535d04524de6dcc92bc13ec532f900ac7e4cf97d

image

Let me know what you think or if we should revert it

**Comment by nlogozzo** [comment]
Ok i also updated the sidebar design to add #503 as well as just a better design:
image

Now the PR is ready haha :)

**Review by DaPigGuy — APPROVED** [review]

**Pull request merged**
