### PR TITLE
GNOME - Fix Help "Document Not Found"

### LINKED ISSUE #759: Help Documents not found
I tried to import a CSV. It said there were no transactions found. I clicked help on the pop-up. I got this error.

Document Not Found. The URI ‘help:tagger/import-export’ does not point to a valid page. Search for packages containing this document.

I'm using the latest Flatpak version.

```
org.nickvision.money
2023.11.0
GTK 4.12.4
libadwaita 1.4.2
Flatpak
en-GB
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

### PR DESCRIPTION
**Pull request by DaPigGuy**
Close #759

### CODE REVIEW

**Comment by nlogozzo** [comment]
Oh...that'll definitely do it 😅

**Review by nlogozzo — APPROVED** [review]

**Comment by JoseBritto** [comment]
Hey,maybe this is just me but I still get this when not using builder. Also our flatpak builds were working fine earlier and are still working the same way.
image

**Comment by JoseBritto** [comment]
Nvm, it was something wrong on my end. AUR git version works fine now. The older stable version shows document not found.

**Comment by nlogozzo** [comment]
> Hey,maybe this is just me but I still get this when not using builder.

Yeah you need to have the app "installed" on the system for it to install the docs in the right place for local builds to find it.
Builder just runs the app, not installs it.

**Pull request merged**
