### PR TITLE
Docs 2023.4.1

### PR DESCRIPTION
**Pull request by fsobolev**
- [x] GroupRGBA field in CSV
- [x] UseGroupColor field in CSV
- [x] Notes in transactions
- [x] Native digits setting
- [x] Export all/current view
- [x] Update Docs HTML
- [x] Update GNOME screenshots
- [x] Update WinUI screenshots

### CODE REVIEW

**Comment by oscfdezdz** [comment]
Should I push the Spanish translation of Docs here?

**Comment by nlogozzo** [comment]
> Should I push the Spanish translation of Docs here?

Yes that'll work :)

**Comment by oscfdezdz** [comment]
I thought I would have permission by joining the organization, but apparently not. Here it is https://github.com/NickvisionApps/Denaro/pull/457

**Comment by nlogozzo** [comment]
> I thought I would have permission by joining the organization, but apparently not. Here it is https://github.com/NickvisionApps/Denaro/pull/457

Ah sorry I thought you would too...I'll give u write access to the repo for next time when I get on my PC :)

**Review by nlogozzo — APPROVED** [review]

**Comment by oscfdezdz** [comment]
> @oscfdezdz let me know if you want to also get notifications about Spanish translation changes.

Yes, I want to receive notifications as well 😄

**Comment by fsobolev** [comment]
> itstool automatically adds "translator-credits" key in *.po files that should be used to add credits to pages... But for some reason when creating a translated page it doesn't add them. I didn't find a way to fix or work around this, so for now translator credits are only in *.po files.

Fixed, turns out translator credits string should contain year and at least `<>` for email, then the string is valid and pasted into pages.

**Review by nlogozzo — APPROVED** [review]

**Pull request merged**
