### PR TITLE
Don't allow groups with whitespace names

### LINKED ISSUE #730: Invisible groups with whitespace name can be created
The groups exist and another one with the same name cannot be create, but they are not visible. And they are also meaningless.

### PR DESCRIPTION
**Pull request by UrtsiSantsi**
Otherwise invisible groups will be added. Fixes #730.

### CODE REVIEW

**Comment by DaPigGuy** [comment]
There are a bunch more instances of this issue if you would like to go ahead and fix those, e.g. account name

**Review by DaPigGuy — APPROVED** [review]

**Comment by nlogozzo** [comment]
Yeah honestly you can probably replace every IsNullOrEmpty with IsNullOrWhitespace

**Comment by nlogozzo** [comment]
Hi @UrtsiSantsi ,

any update on this?

**Comment by JoseBritto** [comment]
@nlogozzo Since op isn't responding, can you merge this for now and I will go ahead and fix the rest in a separate pr

**Comment by nlogozzo** [comment]
Closing in favor of #735

**Pull request closed without merging**
